name: Build AutoClicker

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Unzip source
      run: |
        # Распаковываем исходный код
        Expand-Archive -Path autoclicker_src.zip -DestinationPath .
        # Удаляем архив
        Remove-Item autoclicker_src.zip

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller==5.13.0
        pip install pywin32==306
        pip install pyqt5==5.15.7

    - name: Compile application
      run: |
        pyinstaller --onefile --noconsole --name AutoClicker --clean main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: AutoClicker
        path: dist/AutoClicker.exe
